// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TonedChat.Web.Data;

#nullable disable

namespace TonedChat.Web.Data.Migrations
{
    [DbContext(typeof(TautDatabaseContext))]
    [Migration("20250220002216_AddGeneralChannel")]
    partial class AddGeneralChannel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("TonedChat.Web.Data.Entities.ChannelEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CreateDate")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("create_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("UpdateDate")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("update_date");

                    b.HasKey("Id")
                        .HasName("pk_channel");

                    b.ToTable("channel", (string)null);
                });

            modelBuilder.Entity("TonedChat.Web.Data.Entities.ChatMessageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("ChannelId")
                        .HasColumnType("TEXT")
                        .HasColumnName("channel_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("content");

                    b.Property<string>("CreateDate")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("create_date");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<string>("UpdateDate")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("update_date");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_chat_message");

                    b.HasIndex("ChannelId")
                        .HasDatabaseName("ix_chat_message_channel_id");

                    b.ToTable("chat_message", (string)null);
                });

            modelBuilder.Entity("TonedChat.Web.Data.Entities.ChatMessageEntity", b =>
                {
                    b.HasOne("TonedChat.Web.Data.Entities.ChannelEntity", "Channel")
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chat_message_channel_channel_id");

                    b.Navigation("Channel");
                });
#pragma warning restore 612, 618
        }
    }
}
